### ISSUE TITLE
Scrolling feature needed in fragments

### ISSUE THREAD

**Issue by knightcube** [florent37/ShapeOfView#1]
In some phones, the views cannot be seen properly. Putting things inside a ScrollView would help.

**Comment by florent37** [comment]
oh, just for the sample...

**Comment by knightcube** [comment]
So can i work on the sample codebase?

**Comment by florent37** [comment]
i added a scrollview on the sample

**Comment by knightcube** [comment]
can i work on some other issue sir?

**Comment by florent37** [comment]
you can add others issues if you want

**Comment by knightcube** [comment]
I was actually looking for such a library for pretty long and now since you have come up with it i wanted to contribute in some way. I just wanted to know should i focus on the sample app or on making new shapes?

**Comment by florent37** [comment]
You Can try to create some useful shapes

Le 23 févr. 2018 17:12, "Rajat Kumar Gupta" <notifications@github.com> a
écrit :

**Comment by knightcube** [comment]
Okay i will try to do so
