### ISSUE TITLE
RoundRectView There is a problem with the rounded corners

### ISSUE THREAD

**Issue by pencilso** [florent37/ShapeOfView#12]
RoundRectView：
![screenshot_20180425-114857](https://user-images.githubusercontent.com/16483654/39225456-0e77b586-487f-11e8-91bb-32c5eb27eab0.jpg)
XmlRadius:
![screenshot_20180425-114738](https://user-images.githubusercontent.com/16483654/39225473-1faf50ca-487f-11e8-8090-ebf25f005d0c.jpg)
It seems that RoundRectView does not support full circle angle.

//RoundRectView info
<com.github.florent37.shapeofview.shapes.RoundRectView
                android:layout_width="92dp"
                android:layout_height="28dp"
                android:layout_centerHorizontal="true"
                android:layout_centerVertical="true"
                ro:shape_roundRect_bottomLeftRadius="14dp"
                ro:shape_roundRect_bottomRightRadius="14dp"
                ro:shape_roundRect_topLeftRadius="14dp"
                ro:shape_roundRect_topRightRadius="14dp">

//Shape Xml info
![qq 20180425115741](https://user-images.githubusercontent.com/16483654/39225600-ebbdc8c2-487f-11e8-8227-eb9f8eb878be.jpg)

**Comment by pencilso** [comment]
//RoundRectView info
<com.github.florent37.shapeofview.shapes.RoundRectView
                android:layout_width="92dp"
                android:layout_height="28dp"
                android:layout_centerHorizontal="true"
                android:layout_centerVertical="true"
                ro:shape_roundRect_bottomLeftRadius="14dp"
                ro:shape_roundRect_bottomRightRadius="14dp"
                ro:shape_roundRect_topLeftRadius="14dp"
                ro:shape_roundRect_topRightRadius="14dp">

//Shape Xml info
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <corners android:radius="14dp" />
    <solid android:color="#21000000" />
</shape>

**Comment by florent37** [comment]
I see, I think it's because I do not use arc but another method, i'll try
to fix it

**Comment by pencilso** [comment]
No way
![qq 20180518144258](https://user-images.githubusercontent.com/16483654/40220062-6d0d515e-5aaa-11e8-9626-8a4738772635.jpg)

**Comment by florent37** [comment]
i fixed it in 1.0.9, check the result : 
<img width="335" alt="capture d ecran 2018-05-22 a 18 25 29" src="https://user-images.githubusercontent.com/5754972/40376058-aa214ea6-5ded-11e8-9910-72f86911680c.png">

**Comment by florent37** [comment]
can you try again ?

**Comment by pencilso** [comment]
good
