### ISSUE TITLE
Border for round view?

### ISSUE THREAD

**Issue by frankenten13** [florent37/ShapeOfView#13]
Hi, i usually use custom round view in my app. Can you support RoundView with borderWidth and borderColor like CircleView?
Thanks

**Comment by florent37** [comment]
You have CircleShape

**Comment by frankenten13** [comment]
Sorry, I mean <com.github.florent37.shapeofview.shapes.RoundRectView> with custom radius, not circle

**Comment by florent37** [comment]
implemented to 1.0.8, you can use it ;)
