### ISSUE TITLE
Dynamically Resizing

### ISSUE THREAD

**Issue by victor-m-1994** [florent37/ShapeOfView#14]
I've attempted to resize the view after it was initally set using .setClipPathCreator(Path path), however it only seems to resize the view when an EditText is pressed and pops up the keyboard. Does anybody know how to force the views to resize? Tried .forceLayout(), .invalidate(), and requestLayout() to no avail.

**Comment by florent37** [comment]
I'll try to fix it

**Comment by florent37** [comment]
fixed in 1.0.9, you can use animations if you want, look at AnimationActivity

**Comment by florent37** [comment]
![shapeofview_anim](https://user-images.githubusercontent.com/5754972/40416925-dc6b8e58-5e7e-11e8-8be8-c9cf53e6bf78.gif)
