### ISSUE TITLE
mask can be seen on android 4.4.2

### ISSUE THREAD

**Issue by martipello** [florent37/ShapeOfView#16]
using the arc i get a black mask showing on the left and right (where the arc is) of the view this is only showing up on android 4.4.2 
have tried changing the order of the views inside and outside the view group to no avail

**Comment by florent37** [comment]
can you send an image ?

**Comment by martipello** [comment]
OBVIOUSLY!!! What a stupid thing to do, sorry to have wasted your time (I knew it would be my problem not your libraries) many thanks

**Comment by florent37** [comment]
Thanks you for using my lib :)
