### ISSUE TITLE
Library not working in Android 9 Pie

### ISSUE THREAD

**Issue by hoanganhtuan95ptit** [florent37/ShapeOfView#25]
I use the library on my application, the library is fantastic. On other versions it worked normally, but on android 9 pie it did not work

**Comment by florent37** [comment]
I do not have an Android Pie. I will try on an émulator

Le jeu. 9 août 2018 à 17:47, Hoàng Anh Tuấn <notifications@github.com> a
écrit :

**Comment by florent37** [comment]
fixed ! you can try the 1.3.0

**Comment by hoanganhtuan95ptit** [comment]
It was working normally, thanks for your enthusiastic support, thank  you very much`
