### ISSUE TITLE
High API level required in version 1.3

### ISSUE THREAD

**Issue by ali-star** [florent37/ShapeOfView#26]
I'm using version 1.2.0 right now and today im upgraded the library to version 1.3.0 and I get error about min sdk version of my app (17) because new version requires API level 19, any help?

**Comment by florent37** [comment]
Yes the 1.3 use new path api. It représente 95% of thé store

**Comment by ali-star** [comment]
last version was work's good, why you don't use the new path api for android 4.4 and up, and the old api for older android versions?

**Comment by florent37** [comment]
I coule do that,
But discutting with Romain Guy fromage Google I was using a hack on below
4.4...


But I'll try to do that tout allow user not change the min version

**Comment by ali-star** [comment]
thanks, what is the next version release date?

**Comment by florent37** [comment]
just done ;)
