### ISSUE TITLE
BubbleView needs setter

### ISSUE THREAD

**Issue by xoex** [florent37/ShapeOfView#49]
Hi.
[BubbleView ](https://github.com/florent37/ShapeOfView/blob/master/shapeofview/src/main/java/com/github/florent37/shapeofview/shapes/BubbleView.java)lack setter for arrow height and weight.

```
    public void setArrowHeightPx(int arrowHeightPx)
    {
        this.arrowHeightPx = arrowHeightPx;
    }

    public void setArrowWidthPx(int arrowWidthPx)
    {
        this.arrowWidthPx = arrowWidthPx;
    }

```

**Comment by xoex** [comment]
I see my problem, This functions are available in repository, but you didn't released it. 
I was using 1.0.7 version till now.

**Comment by florent37** [comment]
published
