### ISSUE TITLE
version 1.4.6 is getting Gradle failed to build

### ISSUE THREAD

**Issue by hemandroid** [florent37/ShapeOfView#51]
`Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:10:5-25:19 to override.
`

**Comment by meloveself94** [comment]
same issue even after trying to add multiDexEnabled  = true, delete .gradle folder and also clean project > rebuild project

**Comment by shidiqbagoes** [comment]
Just migrate to android x by doing refactor
Refactor>Migrate to androidX>Do Refactor and don't forget to backup you files

**Comment by florent37** [comment]
the 1.4.6 uses androidX as say @shidiqbagoes just migrate
