### ISSUE TITLE
Ripple effect problem

### ISSUE THREAD

**Issue by msayan** [florent37/ShapeOfView#9]
Hello,
Thanks for great library, i want to ask you a question,
How can i add ripple effect to DiagonalView.

Thanks.

**Comment by florent37** [comment]
Did you try ''selectableItemBackground'' ??

Le mer. 4 avr. 2018 à 16:29, Mehmet Ayan <notifications@github.com> a
écrit :

**Comment by msayan** [comment]
Hello, i try it with the view but it didn't work, then i put some other views inside DiagonalView and add selectableItemBackground to child views and it works.

Thanks for reply.
